name: Build FATE Utils Windows

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'source branch'
        required: true
      type:
        description: 'publish type, test or testpypi or pypi'
        required: false
        default: 'test'

jobs:
  build_windows:
    name: ${{ matrix.python-version }} - windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
    - shell: msys2 {0}
      run: |
        pacman -S pacman-mirrors
        pacman -S diffutils make mingw-w64-x86_64-gcc
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.inputs.source}}
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: windows-maturin
      uses: messense/maturin-action@v1
      with:
        command: build
        working-directory: rust/fate_utils/
        args: --release -i python${{ matrix.python-version }} -o ../../dist
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
